### ISSUE TITLE
Instalação

### ISSUE THREAD

**Issue by wtcosta** [joaoricardorm/tcc#1]
Boa tarde, gostei muito do sistema que você descreveu e do que pude ver no código, porém segui todos os passos que vc descreveu na instalação e não funcionou, quando tento acessar via url está retornando uma tela branca, você poderia me ajudar?

Ps. Estou testando em ambiente local e o caminho do arquivo que você mencionou "/tcc/configuracao_servidor.php" para configurar os dados do BD não existe.

Grato pela atenção...

**Comment by joaoricardorm** [comment]
Opa, tudo bem?
Realmente, estão faltando dois arquivos cruciais para o funcionamento do sistema no GitHub.
Assim que possível realizar o envio.

**Comment by wtcosta** [comment]
Opa amigo, obrigado pelo retorno, estou de fato precisando mesmo de uma base para tocar um projeto aki na empresa e esse seu código iria me ajudar muito no entendimento da ferramentas e algumas funcionalidades.

Estarei ansioso aguardando...

Mais uma vez obrigado!

**Comment by joaoricardorm** [comment]
Bom dia,
fiz o envio dos arquivos que faltavam. São dois, na raiz do projeto:

```
_machine_config.php
configuracao_servidor.php
```

Apenas coloque suas informações do banco de dados em configuracao_servidor.php.
No _machine_config.php não precisa alterar nada. Apenas se quiser mudar o nome da pasta do projeto (em vez de tcc), você terá que alterar na linha 56 e colocar o nome da nova pasta:

`GlobalConfig::$ROOT_URL = RequestUtil::GetServerRootUrl() . 'tcc/';`

**Comment by wtcosta** [comment]
Valew amigo pela força, mais tarde vou testar, qualquer coisa te pertubo mais... rsrsrsrs

Se precisar de alguma força ai com joomla, estarei disponível...

Mais uma vez obrigado pela atenção!
